import type { NextPage } from 'next'
import dynamic from 'next/dynamic'

import Head from 'next/head'

import styles from '../styles/Mint.module.scss'

const Mint: NextPage = () => {
    const MapWithNoSSR = dynamic(() => import("../components/map/Map"), {
        ssr: false,
});
    return (
        <div className={styles.container}>
            <Head>
                <title>Homem Primata Underground NFT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <div className={styles.headerFalse}></div>
            <MapWithNoSSR/>
        </div>
    )
}

export default Mint;