import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Link from 'next/link'

import Head from 'next/head'

import styles from '../styles/Mint.module.scss'

import { Card, CardTitle, CardContent } from '../components/card/Card'

const Mint: NextPage = () => {
    const MapWithNoSSR = dynamic(() => import("../components/map/Map"), {
        ssr: false,
});
    return (
        <div className={styles.container}>
            <Head>
                <title>Homem Primata Underground NFT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <div className={styles.menu}>
                <span onClick={() => {console.log("Hi")}}>
                    <Link href="/"><a href="">
                        <h2>VOLTAR</h2>
                    </a></Link>
                </span>

                <Card>
                    <CardTitle><h3>Informações sobre a coleção:</h3></CardTitle>
                    <CardContent>
                        <h4>DISCOS EMITIDOS: 0/50.000</h4>
                        <h4>FASE ATUAL: 0/10</h4>
                        <h4>PRÓXIMA FASE: 10.000</h4>
                    </CardContent>
                </Card>

                <Card>
                    <CardTitle><h3>Informações sobre a encruzilhada:</h3></CardTitle>
                    <CardContent>
                        <h4>DISCOS EMITIDOS AQUI: 0</h4>
                        <h4>TEMPO RESTANTE: 00,00s</h4>
                        <h4>PESSOAS ONLINE: 0</h4>
                        <h4>ID: 0</h4>
                    </CardContent>
                </Card>

                <Card>
                    <CardTitle><h3>Lorem, ipsum dolor.</h3></CardTitle>
                    <CardContent><h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</h4></CardContent>
                </Card>

            </div>
            <MapWithNoSSR/>
        </div>
    )
}

export default Mint;