import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Link from 'next/link'

import Head from 'next/head'

import styles from '../styles/Mint.module.scss'

import { Card, CardTitle, CardContent } from '../components/card/Card'
import { useState } from 'react'

const Mint: NextPage = () => {
    const [menuIsOpen, setMenu] = useState(false)
    
    const MapWithNoSSR = dynamic(() => import("../components/map/Map"), {ssr: false,})

    const menuClassname = menuIsOpen ?
        `${styles.menu} ${styles.menuOpen}`
        : styles.menu;

    const toggleMenu = () => {
        setMenu(!menuIsOpen)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Homem Primata Underground NFT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <span className={styles.dropdownAction} onClick={toggleMenu}>
                <h1>^</h1>
            </span>
            
            <div className={menuClassname}>
                <span onClick={toggleMenu}>
                    <h2>X</h2>
                </span>

                <Card>
                    <CardTitle><h3>Informações sobre a coleção:</h3></CardTitle>
                    <CardContent>
                        <h4>DISCOS EMITIDOS: 0/50.000</h4>
                        <h4>FASE ATUAL: 0/10</h4>
                        <h4>PRÓXIMA FASE: 10.000</h4>
                    </CardContent>
                </Card>

                <Card>
                    <CardTitle><h3>Informações sobre a encruzilhada:</h3></CardTitle>
                    <CardContent>
                        <h4>DISCOS EMITIDOS AQUI: 0</h4>
                        <h4>TEMPO RESTANTE: 00,00s</h4>
                        <h4>PESSOAS ONLINE: 0</h4>
                        <h4>ID: 0</h4>
                    </CardContent>
                </Card>

                <Card>
                    <CardTitle><h3>Lorem, ipsum dolor.</h3></CardTitle>
                    <CardContent><h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</h4></CardContent>
                </Card>

                <Card>
                    <CardTitle><h3>Lorem, ipsum dolor.</h3></CardTitle>
                    <CardContent><h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</h4></CardContent>
                </Card>

            </div>
            <MapWithNoSSR/>
        </div>
    )
}

export default Mint;